### ISSUE TITLE
Client::__call() arguments

### ISSUE THREAD

**Issue by MGatner** [KnpLabs/php-github-api#1003]
I would be happy to submit a PR but I want to make sure this is a bug first... `Client::__call()` allows magic access to `api('name')`, however the `$args` parameter is not passed into the subsequent object: https://github.com/KnpLabs/php-github-api/blob/2e635fcbc90e224f332cc0ae23e96127d301b4ee/lib/Github/Client.php#L383-L386

This seems a mistake to me, yes?

**Comment by acrobat** [comment]
Hi @MGatner, the `Client::__call` method is used so users of the library can do `$client->users()`. Then they receive the user api class and can call a specific endpoint afterwards (with arguments). Forexample `$client->users()->show(xxx)`. 

The `__call` method receives [by default (php default)](https://www.php.net/manual/en/language.oop5.overloading.php#object.call) the method name and the arguments to it, but for our implementation the `$name` value is only needed so that we can lookup and instantiate the correct class. Also the api classes don't have any required constructor arguments, so there is no need to pass the arguments to the api class.

So this is expected behaviour and not a bug. But thanks for raising the issue!

**Comment by MGatner** [comment]
Gotcha! Thanks for explaining. I guess there would be no way of knowing where to direct `$args` anyway, so that makes sense.
