### ISSUE TITLE
Unable to generate oauth token

### ISSUE THREAD

**Issue by emersonthis** [KnpLabs/php-github-api#305]
I suspect I may be misunderstanding the documentation, but I'm currently unable to get a token using the Authorizations api. Here's what I'm doing:

```
    $data = array(
        'note' => 'GitHub repository access',
        'scopes' => ['repo'],
        'client_id' => $client_id,
        'client_secret' => $client_secret,
        //'fingerprint' => ''
    );
    $github = new \Github\Client();
    $authenticate = $github->authenticate( $client_id, $client_secret, Github\Client::AUTH_URL_CLIENT_ID);
    $authorize = $github->api('authorizations')->create($data);
    var_dump($auth);exit;
```

I get: `Fatal error: Uncaught exception 'Github\Exception\RuntimeException' with message 'Requires authentication'  ...`. I've double-checked the client id and client secret and they're correct. Am I doing something wrong?

**Comment by emersonthis** [comment]
I think I see what I was missing... the "Requires authentication" is referring to the my registered gitHub app. (I thought it meant that the client's authentication method hadn't worked). 

But I'm still somewhat confused as to the intended workflow for a 3rd party web app. Do I need to handle the Oauth2 redirection manually first and then store the token? Or does the library have a way to get a token using the authorize api?

**Comment by GrahamCampbell** [comment]
This is kind of unrelated to this package?

**Comment by emersonthis** [comment]
I think part of my issue is trying to clarify what is/isn't part of the library. It may just be a matter of documentation. 

Is the create method of the Authorizations API not designed for this?

**Comment by GrahamCampbell** [comment]
Works fine for me?

**Comment by emersonthis** [comment]
@GrahamCampbell Can you clarify what worked for you? My code example? What is the expected return of `$github->api('authorizations')->create($data);`

**Comment by drupalninja** [comment]
I cannot get this to work either.

**Comment by Anand-Moghe** [comment]
I am also having some trouble with using JWT token.
The actual workflow for how to use the JWT is depicted [here](https://developer.github.com/apps/building-integrations/setting-up-and-registering-oauth-apps/about-authorization-options-for-oauth-apps/)

So anyway, my understanding is one has to first get the Access Token before even trying to do authenticate:

```
gitHubClient->authenticate(
                $jwtToken,
                null,
                $this->gitHubClient::AUTH_JWT
```

There is no way using this library to check if call was successful or not as it does not return anything. So my understanding is that this authentication does not currently work. 
However if one creates a personal access token in the UI and use it ( third parm should be AUTH_HTTP_TOKEN) ... it works fine.

Also after calling this authenticate method using JWT token, if you try to access other github resources using the clients fails. 

is it because the access-token headers are missing ? I am suspecting that after you call the authenticate using JWT token, every subsequent call to access github resources should contain github access token in the header. 

`Authorization: token OAUTH-TOKEN`

Is there a way to do this (add header) using this library ? Is it needed?  How do I insert specific header and header-values using this API Client?

**Comment by wbaizer** [comment]
Hey @stloyd. Can we get an update on this. I have run into the same issue. I am trying to authenticate my github client through use of `Github\Client::AUTH_URL_CLIENT_ID`

I set it up as such:
```
use Http\Adapter\Guzzle6\Client as GuzzleClient;
use Github\Client as GitHubClient;
use Github\HttpClient\Builder as GitHubBuilder;
$builder = new GitHubBuilder(new GuzzleClient);
$github = new GitHubClient($builder, 'machine-man-preview');
$github->authenticate(<client_id>, <client_secret>, GitHubClient::AUTH_URL_CLIENT_ID);
```

and then run a simple command like 

```
$github->api('user')->show('KnpLabs');
```

Once I run that, I am met by the following error

`Github/Exception/RuntimeException with message 'Requires authentication'`

Seems like a couple of people were trying to get this working. Is it just me, or is this still not working?

**Comment by acrobat** [comment]
Closing this issue for now, if anyone is still experiencing issues please open a new issue. Thanks!
