### ISSUE TITLE
Using with private repos

### ISSUE THREAD

**Issue by EmileDMN** [KnpLabs/php-github-api#333]
Sorry if this a stupid question but is the API usable with a private repo? 

It's not clear to me if this is simply a case of using the authorization part of the docs or if it is just not possible to use this with private repositories?

Thanks,

Emile

**Comment by stof** [comment]
yes it is, as long as you are authenticated. If you cannot access the repo (because you are anonymous, or because it is the private repo of someone else), the github API returns a 404.

I suggest you to read the documentation of the Github API to see what can be done with it. This library just provides a way to access it from PHP.

**Comment by EmileDMN** [comment]
OK that's really useful, thanks.
