### ISSUE TITLE
Need API list-comments-in-a-repository.

### ISSUE THREAD

**Issue by sharing-innovations-luong-phuc** [KnpLabs/php-github-api#371]
Dear @cursedcoder,

Because Github API has this API : https://developer.github.com/v3/pulls/comments/#list-comments-in-a-repository.
But I didn't find this API in source. If you know where is it, please tell me soon. 

Thanks sir.

**Comment by bobeagan** [comment]
It is possible [here](https://github.com/KnpLabs/php-github-api/blob/master/lib/Github/Api/PullRequest/Comments.php#L20) but should probably be pulled out to its own method so that it can support the `sort`, `direction`, and `since` parameters.  Also, it is not indicated in the docs currently that this is possible.

**Comment by acrobat** [comment]
The mentioned api method has support for extra parameters by now, so closing this as resolved.
