### ISSUE TITLE
Accessing private repos

### ISSUE THREAD

**Issue by vchav73** [KnpLabs/php-github-api#440]
I am trying to access a private repo using this code: 

```
require_once 'vendor/autoload.php';
$client = new \Github\Client();
$client->authenticate(‘my_client_id’, ‘my_secret’, \Github\Client::AUTH_URL_CLIENT_ID);
print_r($repo = $client->api('repo')->show(‘my_org_id’, ‘my_private_repo’));
```
The above code always returns this:
```
PHP Fatal error:  Uncaught exception 'Github\Exception\RuntimeException' with message 'Not Found' in /home/prod/apps/analytics/server/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php:86
Stack trace:
#0 /home/prod/apps/analytics/server/vendor/php-http/httplug/src/Promise/HttpFulfilledPromise.php(34): Github\HttpClient\Plugin\GithubExceptionThrower->Github\HttpClient\Plugin\{closure}(Object(GuzzleHttp\Psr7\Response))
#1 /home/prod/apps/analytics/server/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php(87): Http\Client\Promise\HttpFulfilledPromise->then(Object(Closure))
#2 /home/prod/apps/analytics/server/vendor/php-http/client-common/src/PluginClient.php(156): Github\HttpClient\Plugin\GithubExceptionThrower->handleRequest(Object(GuzzleHttp\Psr7\Request), Object(Closure), Object(Closure))
#3 /home/prod/apps/analytics/server/vendor/php-http/client-common/src/PluginClient.php(170): Http\Client\Common\PluginClient->Http\Client\Common\{closure}(Object(GuzzleHttp\Psr7\Re in /home/prod/apps/analytics/server/vendor/knplabs/github-api/lib/Github/HttpClient/Plugin/GithubExceptionThrower.php on line 86
```
When I use a public repo it works fine. I've tried using both OAUTH application and personal access tokens but neither are working for me. Is anyone able to access private repos with this package?

**Comment by GrahamCampbell** [comment]
Yes, works fine for me. It's used in production on https://styleci.io/.

**Comment by vchav73** [comment]
Got this to work after some fiddling.

**Comment by devboxr** [comment]
Having the same issue, care to share how you ended up getting this to work?

**Comment by vchav73** [comment]
I had to switch to a different auth method to get it to work. Below is a snippet based on working code. The snippet adds an issue to a Github repo. The github token is generated from your github account. It's in Settings->Personal access tokens.

```
$client = new \Github\Client(); 
$client->authenticate("github user", "github token", \Github\Client::AUTH_HTTP_PASSWORD);
$issue = array('title' => "My issue title", 'body' => "My issue", 'labels' => array('bug'));
$client->api('issue')->create("My github org", "My repo", $issue);
```

**Comment by Nyholm** [comment]
What authentication method did not work? It is a good idea to document this in the read me. 

@chav73 could you create a PR?

**Comment by vchav73** [comment]
I was trying to use AUTH_URL_CLIENT_ID. Possibly I just don't understand GitHub's OAuth flow well enough. In any case, I was in a hurry, gave up, and used AUTH_HTTP_PASSWORD instead. That is all the details I remember as it was over a month ago that this happened.

**Comment by djdavisdt** [comment]
This appears to still be an issue, even with AUTH_HTTP_PASSWORD and Oauth token.

**Comment by acrobat** [comment]
@djdavisdt can you help and debug this a bit more? As I don't have access to a private repository to test this issue

**Comment by ftrotter** [comment]
Hey, now that github allows for free private repos, would it be possible to clearly document how to authenticate using this library?

![screen shot 2019-02-02 at 11 03 05 pm](https://user-images.githubusercontent.com/83133/52172890-c484bd80-273e-11e9-9302-93c4a7bdd2f0.png)

There are three approved mechanisms to authenticate with the github API. Seen here as well as the url to access them. 

It would be lovely to have something which clearly indicated which \Github\Client::AUTH_Something mapped to which. 

It is also very confusing to have a single authentication mechanism that actually multiple valid syntax to use. The Github authentication methods are different. The authentication functions should be different. Of course if you want to keep things working backwards compatible style that is fine, but right now it is really hard to figure out how to authenticate and clean authentication is 90% of the value proposition of using this library instead of php curl, for those of us who want to do something simple, quickly. 

-FT

**Comment by ftrotter** [comment]
For those looking here.. this is what I eventually got to work ising the "Personal access tokens" method:

```
$client = new \Github\Client();
$client->authenticate($github_personal_token,null,\Github\Client::AUTH_URL_TOKEN);
```

After than, things started working.
