### ISSUE TITLE
php-http/client-implementation -- no matching package found

### ISSUE THREAD

**Issue by trip-somers** [KnpLabs/php-github-api#506]
I'm not sure what I'm missing, but I don't see that anyone has raised this issue yet. I'm trying to upgrade from v1.7.1, and I'm running into this dependency error:

```
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - knplabs/github-api 2.0.1 requires php-http/client-implementation ^1.0 -> no matching package found.
    - knplabs/github-api 2.0.0 requires php-http/client-implementation ^1.0 -> no matching package found.
    - Installation request for knplabs/github-api ~2.0 -> satisfiable by knplabs/github-api[2.0.0, 2.0.1].
```

I looked at php-http on Github, and I don't see that package at all. Did it get renamed recently? Is it private? Did something else change that I'm not aware of?

**Comment by trip-somers** [comment]
This worked after I added "php-http/guzzle6-adapter" to my composer.json.

**Comment by Nyholm** [comment]
`php-http/client-implementation` is a virtual package. See our readme or http://docs.php-http.org/en/latest/httplug/users.html

**Comment by vickygillsf** [comment]
This worked  for me, after I added `"php-http/guzzle6-adapter"`

**Comment by mnapoli** [comment]
I stumbled upon the same problem when trying to install the library. Maybe this library could include a default implementation? This is not really practical as a user because this package is not installable without digging in to understand what this abstraction is about.

**Comment by ultrono** [comment]
> This worked for me, after I added `"php-http/guzzle6-adapter"`

Lifesaver!

**Comment by anil3a** [comment]
> This worked after I added "php-http/guzzle6-adapter" to my composer.json.

Still using this to fix it, Thanks.

**Comment by GrahamCampbell** [comment]
> Still using this to fix it, Thanks.

There isn't an error though. This package intentionally does not mandate which http package you must use?

**Comment by jdvc** [comment]
What worked for me was deleting my vendor directory and composer.lock then doing a fresh composer install.

**Comment by astorm** [comment]
I come to this issue having stumbled across the same problem, and to suggest into the ~uncaring~ very-busy-with-other-work-ugh-open-source void that users (myself included) should be able to run 

    $ composer require knplabs/github-api

and have an installed version of the package that works, or fails in a way that's more straight forward than the usual pile of composer dependency failures.

**Comment by tacman** [comment]
Ideally this would be able to use the Symfony client by default instead of guzzle.  

I think I got this to work a while back, but forget how.  It was something crazy like installing the libraries one at a time.  There was either an incantation or a curse during the process, but I don't think that made any difference.

**Comment by Nyholm** [comment]
> Ideally this would be able to use the Symfony client by default instead of guzzle.

Exactly! That is why we don't have any dependencies on a client. We let you choose. You can use the symfony 4.4 client if you want to. 

--------

If all these conditions is true at the same time...

1) You dont read the Readme
2) You dont know what composer's "virtual package" is
3) You dont read the composer's output
4) You dont google the error message

... then I understand that one can be frustrated. To change back to actually depend on an implementation is a step away from good software architecture because that violates the dependency inversion principle.
