### ISSUE TITLE
Add Integrations::configure

### ISSUE THREAD

**Issue by Nyholm** [KnpLabs/php-github-api#580]
We need a configure method in the Integations API. See https://developer.github.com/early-access/integrations/user-identification-authorization/

**Comment by m1guelpf** [comment]
@Nyholm So we only need to copy the configure method from other early-access?

**Comment by Nyholm** [comment]
Pretty much. And then make sure we use `application/vnd.github.machine-man-preview+json`

**Comment by acrobat** [comment]
I'm ok with adding this method for the integrations api, but if you use the client as an integration is does not make sense to call the configure method but just set the right header in the constructor because you will not mix both api's.

You are using the new integrations api (different authentication method) and only endpoints who are enabled for integrations to use.

But we can add this to be consistent with the other preview features
