### ISSUE TITLE
CONTRIBUTING.md // CODE_OF_CONDUCT.md // ISSUE_TEMPLATE.md

### ISSUE THREAD

**Issue by Geolim4** [KnpLabs/php-github-api#610]
Hello Folks,

Do you guys already thinking about setting up those useful files (Especially the ISSUE_TEMPLATE.md) ?
It'll help you to get a better interaction with your community && a better issue workflow.

Cheers,
Georges

**Comment by Geolim4** [comment]
The Projects feature would lets you construct a nice public roadmap, just like I [did](https://github.com/PHPSocialNetwork/phpfastcache/projects/1) on my project.

**Comment by Geolim4** [comment]
Need help on this ?

**Comment by acrobat** [comment]
You can always send us a pullrequest so we can discuss the actual changes there! But I think I can say we are open to these additions!

**Comment by Geolim4** [comment]
The PR has been delivered as request, let's discuss about it on the [PR page](https://github.com/KnpLabs/php-github-api/pull/730) :)

**Comment by Geolim4** [comment]
@acrobat @Nyholm bump :)

**Comment by acrobat** [comment]
@Geolim4 I will try to review this in the weekend!

**Comment by Geolim4** [comment]
You forgot me ? :P

**Comment by acrobat** [comment]
I'm closing this issue for now. As indicated by @Nyholm in #730 we should just follow the symfony CoC instead of creating a new one. (as this one is well thought out and used by a large community)

Also as mentioned before we don't really see the need for issue/pr templates as we can currently manage the incoming PR's and issues.

But thanks for bringing up this topic!
