### ISSUE TITLE
How to access installation by id?

### ISSUE THREAD

**Issue by Bizarrus** [KnpLabs/php-github-api#719]
I've tried to create an GitHub App. The Webhook URL is `https://example.com/update/`; When i start to change a file, GitHub will call the Webhook correctly.

On the JSON response, the `installation->id` are presented. How i can access the repository with this ID?

I want following handling:

- Create/Update/Delete a file
- Commit
- GitHub calls the Webhook
- The Webhook use the installation id
- The Webhook read a configuration file by given installation id
- The Webhook download the repository
- The Webhook generate a documentation for the downloaded repository
- The Webhook upload the generated documentation to the repository with given configuration

**Comment by Bizarrus** [comment]
When i try to get the actual archive, the script will breaks without exceptions:

```php
$owner			= $repository['owner']['login'];
$repo			= $repository['name'];
$reference		= 'refs/heads/master';
$archive = $github->api('repo')->contents()->archive($owner, $repo, 'tarball', $reference);
```

With `try/catch` no exceptions given. `tarball` or `zipball` won't work.

**Comment by acrobat** [comment]
It's been awhile since I've used github apps but irc you should authenticate as an installation, this way you can access these endpoints for the specific installation.

See [Authenticating as an installation docs](https://docs.github.com/en/developers/apps/authenticating-with-github-apps#authenticating-as-an-installation) on github. I'm closing this as it is more an integration issue and the github docs should provide enough info. If there are problems with this library performing the github instructions, please open a new issue!

**Comment by Bizarrus** [comment]
The issue is 3 years old.

Thanks for the very fast reply. The library was already moved to the Trash.
