### ISSUE TITLE
Resource not accessible by integration when creating an issue

### ISSUE THREAD

**Issue by glebstar** [KnpLabs/php-github-api#970]
I create a new issue like this:
`
    $client = new Client();
    $client->authenticate($user->github_token, Client::AUTH_ACCESS_TOKEN);
    $issue = $client->api('issue')->create('glebstar', 'sdays', ['title' => 'The issue title', 'body' => 'The issue body']);
`

but i get error:
Github\Exception\RuntimeException 
Resource not accessible by integration

**Comment by acrobat** [comment]
I'm closing this issue for now as I think it has more to do with how you are authenticated instead of a bug in this library. Please check your code against the [github docs](https://docs.github.com/en/developers/apps/authenticating-with-github-apps#authenticating-as-an-installation)

If there is still a bug with this library, please open a new issue. Thanks!

**Comment by iamaks1993** [comment]
@glebstar Is this resolved for you?

**Comment by glebstar** [comment]
> @glebstar Is this resolved for you?

I don't remember how I decided
