### ISSUE TITLE
HTTP 500 Problem

### ISSUE THREAD

**Issue by samety-dev** [KnpLabs/php-github-api#971]
![image](https://user-images.githubusercontent.com/67427246/108961320-37e02b80-7688-11eb-93e1-69320fb5469b.png)
My Code;
`<?php

// This file is generated by Composer
require_once __DIR__ . '/vendor/autoload.php';

$client = new \Github\Client();
$repos = $client->api('repo')->find('symfony');
echo $repos;
?>`

**Comment by samety-dev** [comment]
The error appears on line 7.

**Comment by acrobat** [comment]
Hi @samety-dev, this issue tracker is used for reporting bugs with the library and for feature requests. To "fix" this specific case, I would suggest looking into the server logs to retrieve detailed information about the specific error happing. There might an syntax error in your code, the api that return an error because the api request limit is reached, etc.
